//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicStore.Web.MusicAlbumMgr {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Album", Namespace="http://schemas.datacontract.org/2004/07/MusicStore.Core")]
    [System.SerializableAttribute()]
    public partial class Album : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlbumArtUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlbumIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MusicStore.Web.MusicAlbumMgr.Artist ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArtistIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MusicStore.Web.MusicAlbumMgr.Genre GenreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GenreIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlbumArtUrl {
            get {
                return this.AlbumArtUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.AlbumArtUrlField, value) != true)) {
                    this.AlbumArtUrlField = value;
                    this.RaisePropertyChanged("AlbumArtUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlbumId {
            get {
                return this.AlbumIdField;
            }
            set {
                if ((this.AlbumIdField.Equals(value) != true)) {
                    this.AlbumIdField = value;
                    this.RaisePropertyChanged("AlbumId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MusicStore.Web.MusicAlbumMgr.Artist Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArtistId {
            get {
                return this.ArtistIdField;
            }
            set {
                if ((this.ArtistIdField.Equals(value) != true)) {
                    this.ArtistIdField = value;
                    this.RaisePropertyChanged("ArtistId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MusicStore.Web.MusicAlbumMgr.Genre Genre {
            get {
                return this.GenreField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreField, value) != true)) {
                    this.GenreField = value;
                    this.RaisePropertyChanged("Genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenreId {
            get {
                return this.GenreIdField;
            }
            set {
                if ((this.GenreIdField.Equals(value) != true)) {
                    this.GenreIdField = value;
                    this.RaisePropertyChanged("GenreId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Artist", Namespace="http://schemas.datacontract.org/2004/07/MusicStore.Core")]
    [System.SerializableAttribute()]
    public partial class Artist : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArtistIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArtistId {
            get {
                return this.ArtistIdField;
            }
            set {
                if ((this.ArtistIdField.Equals(value) != true)) {
                    this.ArtistIdField = value;
                    this.RaisePropertyChanged("ArtistId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Genre", Namespace="http://schemas.datacontract.org/2004/07/MusicStore.Core", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Genre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.LinkedList<MusicStore.Web.MusicAlbumMgr.Album> AlbumsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GenreIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.LinkedList<MusicStore.Web.MusicAlbumMgr.Album> Albums {
            get {
                return this.AlbumsField;
            }
            set {
                if ((object.ReferenceEquals(this.AlbumsField, value) != true)) {
                    this.AlbumsField = value;
                    this.RaisePropertyChanged("Albums");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenreId {
            get {
                return this.GenreIdField;
            }
            set {
                if ((this.GenreIdField.Equals(value) != true)) {
                    this.GenreIdField = value;
                    this.RaisePropertyChanged("GenreId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MusicAlbumMgr.iAlbum")]
    public interface iAlbum {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iAlbum/BrowseAlbum", ReplyAction="http://tempuri.org/iAlbum/BrowseAlbumResponse")]
        MusicStore.Web.MusicAlbumMgr.Album BrowseAlbum(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iAlbum/BrowseAlbum", ReplyAction="http://tempuri.org/iAlbum/BrowseAlbumResponse")]
        System.Threading.Tasks.Task<MusicStore.Web.MusicAlbumMgr.Album> BrowseAlbumAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iAlbum/GetAllAlbumList", ReplyAction="http://tempuri.org/iAlbum/GetAllAlbumListResponse")]
        System.Collections.Generic.LinkedList<MusicStore.Web.MusicAlbumMgr.Album> GetAllAlbumList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iAlbum/GetAllAlbumList", ReplyAction="http://tempuri.org/iAlbum/GetAllAlbumListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.LinkedList<MusicStore.Web.MusicAlbumMgr.Album>> GetAllAlbumListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iAlbum/GetTopSellingAlbums", ReplyAction="http://tempuri.org/iAlbum/GetTopSellingAlbumsResponse")]
        System.Collections.Generic.LinkedList<MusicStore.Web.MusicAlbumMgr.Album> GetTopSellingAlbums(int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iAlbum/GetTopSellingAlbums", ReplyAction="http://tempuri.org/iAlbum/GetTopSellingAlbumsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.LinkedList<MusicStore.Web.MusicAlbumMgr.Album>> GetTopSellingAlbumsAsync(int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iAlbum/CreateAlbum", ReplyAction="http://tempuri.org/iAlbum/CreateAlbumResponse")]
        void CreateAlbum(MusicStore.Web.MusicAlbumMgr.Album album);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iAlbum/CreateAlbum", ReplyAction="http://tempuri.org/iAlbum/CreateAlbumResponse")]
        System.Threading.Tasks.Task CreateAlbumAsync(MusicStore.Web.MusicAlbumMgr.Album album);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iAlbum/EditAlbum", ReplyAction="http://tempuri.org/iAlbum/EditAlbumResponse")]
        void EditAlbum(MusicStore.Web.MusicAlbumMgr.Album album);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iAlbum/EditAlbum", ReplyAction="http://tempuri.org/iAlbum/EditAlbumResponse")]
        System.Threading.Tasks.Task EditAlbumAsync(MusicStore.Web.MusicAlbumMgr.Album album);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iAlbum/FindAlbum", ReplyAction="http://tempuri.org/iAlbum/FindAlbumResponse")]
        MusicStore.Web.MusicAlbumMgr.Album FindAlbum(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iAlbum/FindAlbum", ReplyAction="http://tempuri.org/iAlbum/FindAlbumResponse")]
        System.Threading.Tasks.Task<MusicStore.Web.MusicAlbumMgr.Album> FindAlbumAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iAlbumChannel : MusicStore.Web.MusicAlbumMgr.iAlbum, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iAlbumClient : System.ServiceModel.ClientBase<MusicStore.Web.MusicAlbumMgr.iAlbum>, MusicStore.Web.MusicAlbumMgr.iAlbum {
        
        public iAlbumClient() {
        }
        
        public iAlbumClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iAlbumClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iAlbumClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iAlbumClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MusicStore.Web.MusicAlbumMgr.Album BrowseAlbum(int id) {
            return base.Channel.BrowseAlbum(id);
        }
        
        public System.Threading.Tasks.Task<MusicStore.Web.MusicAlbumMgr.Album> BrowseAlbumAsync(int id) {
            return base.Channel.BrowseAlbumAsync(id);
        }
        
        public System.Collections.Generic.LinkedList<MusicStore.Web.MusicAlbumMgr.Album> GetAllAlbumList() {
            return base.Channel.GetAllAlbumList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.LinkedList<MusicStore.Web.MusicAlbumMgr.Album>> GetAllAlbumListAsync() {
            return base.Channel.GetAllAlbumListAsync();
        }
        
        public System.Collections.Generic.LinkedList<MusicStore.Web.MusicAlbumMgr.Album> GetTopSellingAlbums(int count) {
            return base.Channel.GetTopSellingAlbums(count);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.LinkedList<MusicStore.Web.MusicAlbumMgr.Album>> GetTopSellingAlbumsAsync(int count) {
            return base.Channel.GetTopSellingAlbumsAsync(count);
        }
        
        public void CreateAlbum(MusicStore.Web.MusicAlbumMgr.Album album) {
            base.Channel.CreateAlbum(album);
        }
        
        public System.Threading.Tasks.Task CreateAlbumAsync(MusicStore.Web.MusicAlbumMgr.Album album) {
            return base.Channel.CreateAlbumAsync(album);
        }
        
        public void EditAlbum(MusicStore.Web.MusicAlbumMgr.Album album) {
            base.Channel.EditAlbum(album);
        }
        
        public System.Threading.Tasks.Task EditAlbumAsync(MusicStore.Web.MusicAlbumMgr.Album album) {
            return base.Channel.EditAlbumAsync(album);
        }
        
        public MusicStore.Web.MusicAlbumMgr.Album FindAlbum(int id) {
            return base.Channel.FindAlbum(id);
        }
        
        public System.Threading.Tasks.Task<MusicStore.Web.MusicAlbumMgr.Album> FindAlbumAsync(int id) {
            return base.Channel.FindAlbumAsync(id);
        }
    }
}
